version: "3"
services:
    postgres-maindb:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: postgres
        restart: always

    redis-cache:
        image: redis
        ports:
            - "6379:6379"
