version: "3"
services:
    postgres-maindb:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            PGUSER: postgres
            POSTGRES_PASSWORD: 1234
            PGPASSWORD: 1234
        restart: always

    redis-cache:
        image: redis
        ports:
            - "6379:6379"
